development:
  update_trading_pairs:
    class: UpdateBinanceTradingPairsJob
    queue: default
    schedule: every hour

production:
  update_trading_pairs:
    class: UpdateBinanceTradingPairsJob
    queue: default
    schedule: every hour
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
